info:
  app:
    name: "gym-gateway-server"

spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000
        response-timeout: 10s
      routes:
        - id: gym-crm-service
          uri: lb://gym-crm-service
          predicates:
            - Path=/gym-crm/**
          filters:
            - RewritePath=/gym-crm/(?<path>.*), /$\{path}
        - id: trainer-workload-service
          uri: lb://trainer-workload-service
          predicates:
            - Path=/trainer-workload/**
          filters:
            - RewritePath=/trainer-workload/(?<path>.*), /$\{path}
            
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/gymapp/protocol/openid-connect/certs

server:
  port: 8888

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8070/eureka/

logging:
  level:
    com.netflix.eureka: DEBUG

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"