info:
  app:
    name: "gym-crm-service"
    description: "Gym CRM API"
    version: "1.0.0"

server:
  port: 8180

spring:
  datasource:
    url: jdbc:postgresql://database:5432/gym_crm
    username: ${PSQL_USERNAME}
    password: ${PSQL_PSW}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        default_schema: lab_project
    open-in-view: false

  flyway:
    schemas: lab_project

logging:
  level:
    lab.project.gym: info

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics
          - prometheus

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8070/eureka/

application:
  security:
    jwt:
      ttl: 600000