info:
  app:
    name: "trainer-workload-service"
    description: "Trainer's workload report service"
    version: "1.0.0"

server:
  port: 8082

spring:
  application:
    name: trainer-workload-service
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

  cloud:
    stream:
      function:
        definition: processWorkload
        bindings:
          sendWorkloadData-in-0:
            destination: send-workload
          evictCache-out-0:
            destination: workload-processed
            group: ${spring.application.name}
        kafka:
          binder:
            brokers:
              - kafka:9092

logging:
  level:
    lab:
      project:
        report: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
