spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: ''
    config:
      enabled: false
      discovery:
        enabled: false

  data:
    redis:
      repositories:
        enabled: false

  jpa:
    properties:
      hibernate:
        default_schema: lab_project
        show_sql: true

  flyway:
    enabled: false

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    enabled: false


logging:
  level:
    org.springframework: info
