spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format-sql: true

custom:
  property: "property from dev profile"

resilience4j.circuitbreaker:
    instances:
      trainerService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 3000
        failureRateThreshold: 50
        waitDurationInOpenState: 5000
